### ISSUE TITLE
PrestaShop Fatal error ://

### ISSUE THREAD

**Issue by Liscata** [TransbankDevelopers/transbank-plugin-prestashop-webpay-rest#9]
Can You help me please? I cann't install this module and I don't know why :( 
I haven't any module with "Logger" CLASS

![image](https://user-images.githubusercontent.com/50456136/104435108-48cb5680-558c-11eb-808d-62baa7c25c23.png)

**Comment by gonzunigad** [comment]
Do you have the previous version installed?
This is the new REST plugin. If you have the SOAP plugin installed, you have to remove it first. 

Here we have the instructions in a video: https://www.youtube.com/watch?v=wYa6Wynfimw

**Comment by AstroniumGIT** [comment]
The problem is in the class names. 
Apache log4php package does not have namespaces so it declares a class named "Logger".
Some other module in "modules" directory does the same. So php cannot declare two classes with the same name and produces an error.
In my case, the second module was my own creation, so I refactored my code to have namespaces. Prestashop 1.6 does not fully support namespaces so here is the guide that helped me to resolve this issue https://github.com/gskema/prestashop-1.6-module-boilerplate/blob/master/docs/namespaces.md

I am not familiar with apache/log4php package, but I think that developers should look for another package that supports namespaces. Because any modules that does not use namespaces and have classes with same names would crash the application.

**Comment by msaustral** [comment]
Hi everyone, please try to erase the var->cache-> prod or dev folder (PS 1.7>) and then open it on an incognito window, disable dev mode and try to install again.
